services:
  vote:
    image: luffyxxsenpai/voting:vote
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - voting_network

  worker:
    image: luffyxxsenpai/voting:worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres
    networks:
      - voting_network

  result:
    image: luffyxxsenpai/voting:result
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - voting_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - voting_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - voting_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  voting_network:
    driver: bridge

volumes:
  postgres_data:

