apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-sm-vote-secretfetch
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-vote-sm-store
    kind: ClusterSecretStore
  target:
    name: vote-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: postgres
