apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-vote-sm-store 
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-sm-accesskey 
            key: access-key
          secretAccessKeySecretRef:
            name: aws-sm-accesskey
            key: secret-access-key
